
services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3001:3000"
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=true
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  grafana_data: